-- Create syntax for TABLE 'xj_user'
CREATE TABLE `xj_user` (
  `id` int NOT NULL AUTO_INCREMENT,
  `xj_id` int unsigned NOT NULL COMMENT 'ks号',
  `phone` varchar(11) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL COMMENT '手机号',
  `pwd` varchar(32) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL COMMENT '密码',
  `nickname` varchar(25) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '昵称',
  `brand` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL COMMENT '手机品牌',
  `IMEI` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL COMMENT '手机串号',
  `regdate` datetime NOT NULL COMMENT '注册日期',
  `gender` varchar(6) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT '男' COMMENT '性别',
  `age` tinyint DEFAULT NULL COMMENT '年龄',
  `birthday` varchar(10) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '出生年月日',
  `height` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '身高（厘米）',
  `weight` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '体重（公斤）',
  `email` varchar(30) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '电子邮箱地址',
  `reg_type` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '注册类型  1：手机  2：微信 3：微博 4：QQ 5：邮箱',
  `reg_ip` varchar(15) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '注册ip',
  `avatar` varchar(500) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT '' COMMENT '头像地址',
  `avatar_big` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT '' COMMENT '头像地址',
  `province` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '省份',
  `my_slogan` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT '' COMMENT '个性签名',
  `city` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '城市',
  `extradata` text CHARACTER SET utf8 COLLATE utf8_general_ci COMMENT '扩展字段，一般不用',
  `status` tinyint(1) DEFAULT '1' COMMENT '状态（1，可用；0，禁用）',
  `lng` decimal(15,12) DEFAULT NULL COMMENT '经度',
  `lat` decimal(15,12) DEFAULT NULL COMMENT '纬度',
  `logintime` datetime DEFAULT NULL,
  `last_logintime` datetime DEFAULT NULL COMMENT '最后登录时间',
  `appkey` varchar(225) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT '' COMMENT '商用跑步机appkey',
  `tuuid` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT '' COMMENT '跑步机序列号',
  `guide` tinyint(1) DEFAULT '0' COMMENT '是否设置引导页（0，未设置；1，已设置）',
  `runType` tinyint unsigned DEFAULT '0' COMMENT '跑步机用户表示（0，不是；2，是）',
  `no_phone` tinyint DEFAULT '0' COMMENT '未绑定手机号',
  `unit_of_weight` tinyint DEFAULT '1' COMMENT '重量单位：1公斤，2市斤',
  `guide_a1pro` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT '[]' COMMENT 'a1pro新手引导页',
  `active` tinyint DEFAULT '1' COMMENT '邮箱激活状态 0 未激活 1已激活',
  `deviceToken` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '友盟token',
  `weight_target` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
  PRIMARY KEY (`id`) USING BTREE,
  KEY `ksid` (`xj_id`) USING BTREE,
  KEY `tuuid` (`tuuid`) USING BTREE,
  KEY `email` (`email`) USING BTREE,
  KEY `nickname` (`nickname`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=219551 DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC;

-- Create syntax for TABLE 'xj_user_did'
CREATE TABLE `xj_user_did` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `did` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `xj_id` int DEFAULT NULL,
  `model` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT '',
  `bind_time` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  `add_time` datetime DEFAULT NULL,
  `app` tinyint DEFAULT '1' COMMENT '来源设备',
  `type` tinyint DEFAULT '1' COMMENT '1阿里云iot设备 2米家iot设备 3蓝牙设备',
  `iot_id` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT '',
  `uuid` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT '' COMMENT 'ios设备唯一码',
  `cacheJson` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT '' COMMENT 'app缓存数据',
  `productId` int DEFAULT NULL COMMENT '产品id',
  `name` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT '' COMMENT '设备名称',
  PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC;

-- Create syntax for TABLE 'xj_user_region'
CREATE TABLE `xj_user_region` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `xj_id` int unsigned NOT NULL,
  `reg_ip` varchar(15) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '' COMMENT '注册ip',
  `city_id` int DEFAULT '0',
  `country` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT '',
  `region` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT '',
  `province` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT '',
  `city` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT '',
  `isp` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT '',
  `decode_body` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `xj_id` (`xj_id`),
  KEY `reg_ip_city_id` (`city_id`),
  KEY `reg_ip_country` (`country`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;