[app]
name = "KS-HORIZON"
port = "3333"
[mysql]
host = "127.0.0.1"
port = "3306"
user = "root"
pass = "123456"
dbname = "ks_horizon"
charset = "utf8"

[redis]
host = "127.0.0.1"
port = "6379"
db = "1"