// Package restapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.9.0 DO NOT EDIT.
package restapi

// Did defines model for did.
type Did struct {
	Did   string `json:"did" boil:"did"`
	Id    int    `json:"id" boil:"id"`
	Model string `json:"model" boil:"model"`
	Name  string `json:"name" boil:"name"`
	XjId  int    `json:"xj_id" boil:"xj_id"`
}

// Pagination defines model for pagination.
type Pagination struct {
	PageNum  int `json:"page_num" boil:"page_num"`
	PageSize int `json:"page_size" boil:"page_size"`
	Total    int `json:"total" boil:"total"`
}

// User defines model for user.
type User struct {
	Age      *int    `json:"age" boil:"age"`
	Birthday *string `json:"birthday,omitempty" boil:"birthday"`
	Email    *string `json:"email" boil:"email"`
	Gender   *string `json:"gender,omitempty" boil:"gender"`
	Height   *string `json:"height,omitempty" boil:"height"`
	Nickname *string `json:"nickname,omitempty" boil:"nickname"`
	Phone    *string `json:"phone,omitempty" boil:"phone"`
	RegIp    *string `json:"reg_ip,omitempty" boil:"reg_ip"`
	RegType  *string `json:"reg_type,omitempty" boil:"reg_type"`
	XjId     int     `json:"xj_id" boil:"xj_id"`
}

// GetDidsParams defines parameters for GetDids.
type GetDidsParams struct {
	Limit string `json:"limit" boil:"limit"`
	Page  string `json:"page" boil:"page"`
}

// GetUsersJSONBody defines parameters for GetUsers.
type GetUsersJSONBody struct {
	Limit int `json:"limit" boil:"limit"`
	Page  int `json:"page" boil:"page"`
}

// GetUsersJSONRequestBody defines body for GetUsers for application/json ContentType.
type GetUsersJSONRequestBody GetUsersJSONBody
