// Code generated by SQLBoiler 4.8.3 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package persistence

var TableNames = struct {
	XJUser       string
	XJUserDid    string
	XJUserRegion string
}{
	XJUser:       "xj_user",
	XJUserDid:    "xj_user_did",
	XJUserRegion: "xj_user_region",
}
